<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NaturalCron" Version="0.2.0" />
      <PackageReference Include="Quartz" Version="3.14.0" />
    </ItemGroup>

</Project>
